spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://zipkin:9411
  cloud:
    compatibility-verifier:
      enabled: false
server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

  dashboard:
    path: /dashboard
  instance:
    hostname: localhost